Attempt to partially update team listings
QuiltMC/quiltmc.org pull request #112
Opened 2023-03-05 15:54 UTC by EnnuiL

This covers the changes to the QSL team's structure, and also new folks on the QFAPI team and Mappings Triage

2023-03-05 16:04 UTC, BucketOfCompasses commented
Minor nitpick but the core team is mentioned to be a subteam of QSL but isn't listed as such 

e.g. subteams have the heading "## Sub-Team: TEAM NAME HERE" where as core has the heading "## Core (Team Leaders)"

Also the overall team may need a better name as it may get confusing trying to tell if someone is referring the subteam or the overall team.

"**The QSL team** is divided into three subteams: the Core team, **the QSL team** and Quilted Fabric API."

2023-03-05 17:09 UTC, Southpaw1496 requested changes
When the team was working on the restructure, did you consider the confusion that might arise from having the QSL team as a sub team of the QSL team?

2023-03-05 17:09 UTC, Southpaw1496 commented on src/pages/en/about/teams.mdx
> +The QSL team is divided into three subteams: the Core team, the QSL team and Quilted Fabric API.
```suggestion
The QSL team is divided into three subteams: the Core team, the QSL team and Quilted Fabric API team.
```

2023-03-05 17:12 UTC, EnnuiL commented
> When the team was working on the restructure, did you consider the confusion that might arise from having the QSL team as a sub team of the QSL team?

Yes I have and I complained about the current naming scheme on an internal chat; I feel like establishing proper naming for the teams will be mandatory for this PR

2023-03-05 17:14 UTC, Southpaw1496 commented
Should it be converted to a draft, then, while you figure that out?

2023-03-05 17:15 UTC, EnnuiL commented
> Should it be converted to a draft, then, while you figure that out?

fair enough

2023-04-15 12:05 UTC, Akarys42 commented
Closed in favor of #117

2023-04-15 12:05 UTC, closed without merging