blog: post about the newly merged MAU beacon rfc
QuiltMC/quiltmc.org pull request #140
Opened 2023-06-21 18:06 UTC by ix0rai

a quick explainer, mostly for those who are concerned about their privacy

2023-06-21 20:50 UTC, Akarys42 commented
Preview: https://quiltmc.org/en/blog/2023-06-21-mau-beacon/

2023-06-24 22:18 UTC, Akarys42 approved these changes

2023-06-25 22:59 UTC, Akarys42 requested changes

2023-06-25 22:59 UTC, Akarys42 commented on src/pages/en/blog/2023-06-21-mau-beacon.md
> +our counter as per [the restrictions in the RFC](link). The server accepting the signal is [fully open source](https://github.com/QuiltMC/beacon.quiltmc.org)
link needs to be, well, link

2023-06-26 00:36 UTC, Akarys42 approved these changes
Link is now linking

2023-06-26 19:12 UTC, AlexIIL approved these changes

2023-06-27 01:09 UTC, merged