Change Twitter to X
QuiltMC/quiltmc.org pull request #150
Opened 2023-09-06 13:02 UTC by sticks-stuff

Requires https://github.com/QuiltMC/quilt-bulma/pull/13

2023-09-06 14:48 UTC, Southpaw1496 approved these changes
Mostly good except that there's no point changing all of the URLs to x.com since x.com still redirects to twitter.com

2023-09-06 14:48 UTC, Southpaw1496 commented on src/data/Site.ts
> +			new URL("https://x.com/quilt_mc"),
```suggestion
			new URL("https://twitter.com/quilt_mc"),
```
x.com still redirects to twitter.com, changing the URL is pointless.

2023-09-06 14:48 UTC, Southpaw1496 commented on src/data/TeamData.mjs
Changing x.com to twitter.com is pointless since x.com still redirects to twitter.com.

2023-09-06 14:49 UTC, Southpaw1496 requested changes
Mostly good except that there's no point changing all of the URLs to x.com since x.com still redirects to twitter.com

2023-09-06 15:07 UTC, Southpaw1496 requested changes

2023-09-06 15:07 UTC, Southpaw1496 commented on src/data/Site.ts
> +		handle: new SocialMediaHandle("https://x.com/", "quilt_mc"),
Missed one

2023-09-06 15:18 UTC, sticks-stuff commented
Fixed, sorry

2023-09-06 15:19 UTC, Southpaw1496 approved these changes
If we're waiting on the Quilt Bulma PR it may be a little while: that's someone else's job 🙃

2023-09-06 15:22 UTC, sticks-stuff commented
Ah, shame :(

2024-04-16 22:20 UTC, LambdAurora commented
Just saw this PR for some reason.

I'd rather not use a brand that sounds and looks shady af, which is still not that much in people's mind aside of being a joke, to satisfy the ego of some random delusional person who's way too rich for their own good.

2024-04-16 22:20 UTC, closed without merging