Add Modrinth App (fixes #148)
QuiltMC/quiltmc.org pull request #151
Opened 2023-09-10 20:13 UTC by Ecorous

2023-09-10 20:13 UTC, Ecorous commented
fixes #148

2023-09-10 20:14 UTC, Southpaw1496 commented
Thank you so much for saving me this job 😅 

Would you be able to rebase with the main branch?

2023-09-10 23:41 UTC, OroArmor approved these changes

2023-09-10 23:47 UTC, ix0rai commented
should we advise about the version ordering, or have they fixed it?

2023-09-11 07:06 UTC, Ecorous commented
> should we advise about the version ordering, or have they fixed it?

That's been fixed

2023-09-11 07:09 UTC, Southpaw1496 requested changes
Pretty good, just some wording suggestions.

2023-09-11 07:09 UTC, Southpaw1496 commented on src/pages/en/install/modrinth.mdx
> +The Modrinth App is a unique, open source launcher that allows you to play your favorite mods, and keep them up to date, all in one neat little package.
```suggestion
The Modrinth App is a unique, open source launcher that allows you to play your favorite mods, and keep them up to date, all in one neat little package. To set up your own Quilt profile, simply follow these steps:
```
This is more consistent with the other guides.

2023-09-11 07:09 UTC, Southpaw1496 commented on src/pages/en/install/modrinth.mdx
> +2. Open Modrinth and click on the `+` in the bottom left
```suggestion
2. Open the app and click on the `+` button in the bottom left
```
Saying "Open Modrinth" could be confused with opening the website.

2023-09-11 07:09 UTC, Southpaw1496 commented on src/pages/en/install/modrinth.mdx
> +3. Fill out the Name
```suggestion
3. Give the profile a Name
```

2023-09-11 07:09 UTC, Southpaw1496 commented on src/pages/en/install/modrinth.mdx
> +4. Pick Quilt from the list of modloaders.
```suggestion
4. Pick Quilt from the list of modloaders
```
The full-stop here is inconsistent with the other bullet points.

2023-09-11 07:17 UTC, Ecorous commented
Should be done now.

2023-09-11 07:21 UTC, Southpaw1496 approved these changes

2023-09-11 07:22 UTC, merged