Add Sponsorships page, with list of sponsors and information for how to offer a sponsorship
QuiltMC/quiltmc.org pull request #55
Opened 2022-07-18 15:40 UTC by Southpaw1496

I'm not entirely happy with the formatting yet, I thought it might be nice to have each sponsor's logo next to their entry, but I don't know how to do that elegantly.

2022-09-19 14:29 UTC, gdude2002 commented
"Past Sponsors" makes no sense imo, the point of a sponsorship for many sponsors is we're sending people their way - doesn't really make sense to do that if they're no longer sponsoring us.

2022-09-19 14:31 UTC, Southpaw1496 commented
> "Past Sponsors" makes no sense imo, the point of a sponsorship for many sponsors is we're sending people their way - doesn't really make sense to do that if they're no longer sponsoring us.

As I mentioned in Discord, this page is purely for informational purposes, it's not designed to be an advertisement for the sponsors, which is why Endorsed and non-Endorsed sponsors get equal preference. The advertisement part would go on the homepage and be addressed separately (#68

2022-09-19 14:55 UTC, Southpaw1496 commented
@Akarys42 @Redblueflame Your input would also be appreciated, as the other two people most interested in the sponsorship process. I'm also requesting @pluiedev 's review since I don't really know what I'm doing in terms of Astro yet 🙃

2022-09-19 14:59 UTC, Redblueflame commented
Addressing @gdude2002's comment:
Getting a list of past sponsorships is worth, but we have to make sure that we only put names, not more (link to website ok, but not encouraged)

For that, I think putting past memberships below the fold by putting "How do I sponsor" just above can be a good placement

2022-09-19 15:02 UTC, Southpaw1496 commented
I mean, I don't think a link to the website is problematic, especially as the page is for information and also hidden away in the sidebar. Especially when Endorsed sponsors have their own place on the homepage, I don't think most people will go hunting for that page.

2022-09-19 15:03 UTC, Southpaw1496 commented
I do think we should be keeping the list of sponsors together, but putting them below the "How to be a sponsor" section would be OK if you feel strongly about it.

2022-09-20 03:13 UTC, pluiedev requested changes
Mostly good tech-wise, just a couple nitpicks

2022-09-20 03:13 UTC, pluiedev commented on src/pages/en/sponsors.mdx
> +Starchild Systems is an Infrastructure-as-a-Service company. They host the [Quilt Forum](https://forum.quiltmc.org) on their infrastructure at no cost to us.
The forum link should reuse the URLs set in `Site.ts`.
```mdx
---
# ...
---
import site from "@data/Site";

...

### Starchild Systems (Endorsed)
Starchild Systems is an Infrastructure-as-a-Service company. They host the <a href={site.forum}>Quilt Forum</a> on their infrastructure at no cost to us.
```
We should also add the OpenCollective page to `Site.ts` at some point, but I wouldn't force you to do it :>

2022-09-21 00:07 UTC, pluiedev approved these changes

2022-09-28 12:23 UTC, gdude2002 approved these changes

2022-09-29 10:07 UTC, merged