Change "Openings" to "Help Wanted"
QuiltMC/quiltmc.org pull request #89
Opened 2022-12-06 19:47 UTC by TheGlitch76

We don't want to push joining a team as the primary way to contribute to Quilt. It's not necessary, and we expect people to contribute some *before* joining a team, the opposite of what parts of the website currently suggest.

This PR changes the "Openings" page to a "Help Wanted" page that is hopefully much less intimidating (it only asks for contribution, not accepting responsibility) and more reflective of how contributing to Quilt actually works.

Reviews and rewording is always welcome.

TODO before merge: 
- [ ]  Add a redirect from "openings" to "help-wanted" (I don't know how to do this)
- [ ] Re-do the section on Build Tools

2022-12-13 03:24 UTC, pluiedev requested changes
The wording looks good, though the navbar currently links to the (nonexistent) openings page; also you need to change the English strings ending in `-opening` in `/src/locales/en/common.flt` to reflect this change.

2023-01-29 22:01 UTC, obj-obj commented
You should be able to make a redirect by doing this:

```astro
---
import Redirect from "@layouts/Redirect.astro";
---

<Redirect href="url" />
```

2023-01-30 06:27 UTC, pluiedev approved these changes

2023-01-30 06:27 UTC, pluiedev commented on src/locales/zh/common.flt
> +-help-wanted = Help Wanted (FIXME BEFORE MERGE!!!)
TBH the Chinese translation is there just as a way for me to demonstrate the language switch. I'm not planning to make a full translation so you can leave that as-is for now :p

2023-03-02 15:20 UTC, EnnuiL commented
It appears that this PR stalled, which worries me; I consider it a prerequisite for PR #90

2023-03-07 12:41 UTC, merged

2023-03-07 12:51 UTC, gdude2002 commented
Looks like a bad merge was pushed to `common.flt`, this is going to need fixing pretty quickly

2023-03-07 13:08 UTC, Southpaw1496 commented
Oops. I did check and everything looks fine, but I wasn't really sure if there were any auditing steps to run.

2023-03-07 13:09 UTC, gdude2002 commented
No, you don't get me - you committed a merge conflict without resolving it.